version: "3.8"

services:
    server:
        depends_on:
            - db
        restart: unless-stopped
        build: ./server
        ports:
            - 8080:8080
        environment:
            # site
            DB_URL: "mongodb://db:27017/ExerciseDB"
        networks:
            - server

    db:
        image: mongo:5.0.3
        restart: unless-stopped
        ports:
            - 27017
        volumes:
            - Exercise:/data/db
        networks:
            - server

volumes:
    Exercise:

networks:
    server:
